common/models/Questionnaires.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "questionnaires".
 *
 * @property integer $id
 * @property integer $monthly_budget
 * @property integer $max_cost_conversion
 * @property integer $advise_cost_conversion
 * @property string $context_advertising_type
 * @property integer $plannde_conversion_amount
 * @property string $commodity
 * @property string $commodity_advantages
 * @property string $company_advantages
 * @property string $sales
 * @property string $delivery_condition
 * @property string $message
 * @property string $fio
 * @property string $phone
 * @property string $site_address
 * @property string $advertising_district
 * @property string $advertising_systems
 * @property integer $user_id
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 */
class Questionnaires extends \common\models\BehaviorModel
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'questionnaires';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['monthly_budget', 'max_cost_conversion', 'advise_cost_conversion', 'plannde_conversion_amount', 'user_id', 'created_at', 'updated_at', 'created_by', 'updated_by'], 'integer'],
            [['user_id'], 'required'],
            [['context_advertising_type', 'commodity', 'commodity_advantages', 'company_advantages', 'sales', 'delivery_condition', 'message', 'site_address', 'advertising_district', 'advertising_systems', 'fio','phone'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'monthly_budget' => 'Monthly Budget',
            'max_cost_conversion' => 'Max Cost Conversion',
            'advise_cost_conversion' => 'Advise Cost Conversion',
            'context_advertising_type' => 'Context Advertising Type',
            'plannde_conversion_amount' => 'Plannde Conversion Amount',
            'commodity' => 'Commodity',
            'commodity_advantages' => 'Commodity Advantages',
            'company_advantages' => 'Company Advantages',
            'sales' => 'Sales',
            'delivery_condition' => 'Delivery Condition',
            'message' => 'Message',
            'fio' => 'FIO',
            'phone' => 'Phone',
            'site_address' => 'Site Address',
            'advertising_district' => 'Advertising District',
            'advertising_systems' => 'Advertising Systems',
            'user_id' => 'User ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
        ];
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function beforeValidate() {
        if(is_array($this->advertising_systems)){
            $this->advertising_systems = implode(",", $this->advertising_systems);
        }
        return true;
    }
}

backend/views/layouts/gantelella.php
<?php

/**
 * @var string $content
 * @var \yii\web\View $this
 */

use yii\helpers\Html;
use \yiister\gentelella\widgets\Menu;

$bundle = yiister\gentelella\assets\Asset::register($this);
\backend\assets\AppAsset::register($this);

?>
<?php $this->beginPage(); ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta charset="<?= Yii::$app->charset ?>" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="nav-md">
<?php $this->beginBody(); ?>
<div class="container body">

    <div class="main_container">

        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">

                <div class="navbar nav_title" style="border: 0;">
                    <a href="/" class="site_title"><i class="fa fa-paw"></i> <span>profitpanda.ru</span></a>
                </div>
                <div class="clearfix"></div>

                <!-- menu prile quick info -->
                <div class="profile">
                    <div class="profile_info">
                        <span>Добро пожаловать,</span>
                        <?= Yii::$app->user->identity->username ?>
                    </div>
                    <div class="clear"></div>
                </div>
                <!-- /menu prile quick info -->

                <br />

                <!-- sidebar menu -->
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

                    <div class="menu_section">
                        <?php
                        if (array_key_exists('leftMenuItems', $this->params))
                            echo Menu::widget([
                                'items' => $this->params['leftMenuItems']['items']
                            ]);
                        ?>
                    </div>

                </div>
                <!-- /sidebar menu -->

            </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">

            <div class="nav_menu">
                <nav class="" role="navigation">
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <img src="/img/text.png" alt="">
                                <?= Yii::$app->user->isGuest ? '' : Yii::$app->user->identity->username ?>
                                <span class=" fa fa-angle-down"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-usermenu pull-right">
                                <li>
                                    <?= Html::a('<i class="fa fa-sign-out pull-right"></i> Выйти',
                                        '/site/logout', [
                                        'data' => [
                                            'method' => 'post',
                                        ],
                                    ]) ?>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </nav>
            </div>

        </div>
        <!-- /top navigation -->

        <!-- page content -->
        <div class="right_col" role="main">
                <div class="page-title">

                    <div class="title_left">
                        <div>
                            <?php
                            if (isset($this->params['breadcrumbs'])) {
                                $lastcrumb = end($this->params['breadcrumbs']);
                                foreach ($this->params['breadcrumbs'] as $crumb) {
                                    if ($crumb == $lastcrumb) {
                                        if (is_array($crumb))
                                            echo $crumb['label'];
                                        else
                                            echo $crumb;
                                    } else {
                                        echo Html::a($crumb['label'], $crumb['url']) . ' / ';
                                    }
                                }
                            }
                            ?>
                        </div>
                        <?php
                        if (Yii::$app->session->get('campaignID', false) || Yii::$app->session->get('adgroupID', false)) {
                            $lastcrumb = end($this->params['breadcrumbs']);
                            echo Html::tag('h3', is_array($lastcrumb) ? $lastcrumb['label'] : $lastcrumb);
                        }
                        ?>
                    </div>
                    <div class="title_right"></div>
                </div>
            <div class="clearfix"></div>

            <?= $content ?>
        </div>
        <!-- /page content -->
    </div>

</div>

<div id="custom_notifications" class="custom-notifications dsp_none">
    <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
    </ul>
    <div class="clearfix"></div>
    <div id="notif-group" class="tabbed_notifications"></div>
</div>
<!-- /footer content -->
<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>