common/models/Company.php
<?php

namespace common\models;

/**
 * This is the model class for table "company".
 *
 * @property integer $id
 * @property string $name
 * @property string $website
 * @property string $sales_report_url
 * @property integer $user_id
 * @property integer $created_at
 * @property integer $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property string $token
 * @property integer $last_crm_stat_downloading
 *
 * @property Account[] $accounts
 * @property User $user
 * @property CrmOrder[] $crmOrders
 */
class Company extends \common\models\BehaviorModel
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'company';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'user_id'], 'required'],
            [['user_id', 'created_at', 'updated_at', 'created_by', 'updated_by', 'last_crm_stat_downloading'], 'integer'],
            [['name', 'website', 'sales_report_url', 'token'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'website' => 'Веб-сайт',
            'sales_report_url' => 'Sales Report Url',
            'user_id' => 'User ID',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'created_by' => 'Created By',
            'updated_by' => 'Updated By',
            'token' => 'Token',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccounts()
    {
        return $this->hasMany(Account::className(), ['company_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCrmOrders()
    {
        return $this->hasMany(CrmOrder::className(), ['company_id' => 'id']);
    }
}

backend/controllers/CompanyController.php
<?php

namespace backend\controllers;

use common\models\Account;
use common\models\Goal;
use common\models\service\yandex\Metrika;
use Yii;
use common\models\Company;
use common\models\CompanySearch;
use yii\filters\AccessControl;
use yii\helpers\VarDumper;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Url;

/**
 * CompanyController implements the CRUD actions for Company model.
 */
class CompanyController extends BaseController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ]
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Company models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new CompanySearch();
        $params = Yii::$app->request->queryParams;
        $params['CompanySearch']['user_id'] = Yii::$app->user->id;
        $dataProvider = $searchModel->search($params);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Company model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $direct = Account::find()->where(
            'company_id = ' . $id .
            ' and advert_type = ' . Account::TYPE_YANDEX .
            ' and advert_login is not null and advert_login <> \'\''
        )->one();

        $directMetrikaCounters = [];
        $directSelectedGoals = [];
        $directClientList = false;
        if ($direct != null) {
            $counters = $direct->import->getMetrikaCounters();
            $metrika = new Metrika($direct->stat_token);
            $directMetrikaCounters = array_map(function ($counter) use ($metrika) {
                return [
                    'id' => $counter['id'],
                    'name' => $counter['name'],
                    'goals' => $metrika->getGoals($counter['id'])
                ];
            }, $counters);
            $directSelectedGoals = Goal::find()->select('number')->where(['account_id' => $direct->id])->column();

            $directClientList = $direct->import->getClientList();
        }

        $adwords = Account::find()->where(
            'company_id = ' . $id .
            ' and advert_type = ' . Account::TYPE_GOOGLE .
            ' and advert_login is not null and advert_login <> \'\''
        )->one();
        $customerId = Account::find()
            ->select('client_customer_id')
            ->where(
                'company_id = ' . $id .
                ' and advert_type = ' . Account::TYPE_GOOGLE .
                ' and client_customer_id is not null and client_customer_id <> \'\''
            )->scalar();


        return $this->render('view', [
            'model' => $this->findModel($id),
            'direct' => $direct,
            'adwords' => $adwords,
            'customerId' => $customerId,
            'directMetrikaCounters' => $directMetrikaCounters,
            'directSelectedGoals' => $directSelectedGoals,
            'directClientList' => $directClientList
        ]);
    }

    /**
     * Creates a new Company model.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Company();
        $model->user_id = Yii::$app->user->id;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Company model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Finds the Company model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Company the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Company::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function getBreadcrumbs($view, $model)
    {
        $breadcrumbs = [
            [
                'label' => 'Проекты',
                'url' => Url::to(['/company/index'])
            ]
        ];
        if ($view == 'index')
            return $breadcrumbs;
        elseif ($view == 'create')
            $breadcrumbs[] = 'Добавить';
        elseif ($view == 'view')
            $breadcrumbs[] = $model['model']->name;
        elseif ($view == 'connectCrm') {
            $breadcrumbs[] = [
                'label' => $model['model']->name,
                'url' => Url::to([
                    'company/view',
                    'id' => $model['model']->id
                ])
            ];
            $breadcrumbs[] = 'Подключить CRM';
        }
        elseif ($view == 'update') {
            $breadcrumbs[] = [
                'label' => $model['model']->name,
                'url' => Url::to([
                    'company/view',
                    'id' => $model['model']->id
                ])
            ];
            $breadcrumbs[] = 'Обновить';
        }

        return $breadcrumbs;
    }

    public function actionSaveLogin()
    {
        $accountId = Yii::$app->request->post('id', false);
        $login = Yii::$app->request->post('directClient', false);

        $account = Account::findOne($accountId);
        $account->client_login = $login;
        $account->update();

        return $this->redirect([
            'company/view',
            'id' => $account->company_id
        ]);
    }

    public function actionSaveGoals()
    {
        $accountId = Yii::$app->request->post('id', false);
        $counter = Yii::$app->request->post('counter', false);
        $goals = Yii::$app->request->post('goal', false);
        $account = Account::findOne($accountId);
        $account->counter = $counter;
        $account->update();

        Goal::deleteAll(['account_id' => $accountId]);
        foreach ($goals as $goal) {
            $goal = new Goal([
                'number' => $goal,
                'account_id' => $account->id
            ]);
            $goal->save();
        }

        return $this->redirect([
            'company/view',
            'id' => $account->company_id
        ]);
    }

    public function actionSaveCrm()
    {
        $companyId = Yii::$app->request->post('id', false);
        $crmUrl = Yii::$app->request->post('crm', false);
        $company = Company::findOne(['id' => $companyId]);
        $company->sales_report_url = trim($crmUrl);
        $company->update();

        return $this->redirect([
            'company/view',
            'id' => $companyId
        ]);
    }

    private function tokenRequestYandex($type, $accountId)
    {
        Yii::$app->session->set('accountId', $accountId);
        Yii::$app->session->set('type', $type);
        if ($type == Account::SYSTEM_TYPE_CONTEXT || $type == Account::SYSTEM_TYPE_WEBANALYTICS)
            Yii::$app->response->redirect(
                sprintf('%sauthorize?response_type=code&client_id=%s',
                    Yii::$app->params['services']['yandex']['oauth']['url'],
                    Yii::$app->params['services']['yandex']['direct']['appID'])
            );
    }

    public function actionConnectDirect($id)
    {
        $company = Company::findOne($id);//$company = $this->findModel($id);
        $account = Account::findOne([
            'company_id'  => $company->id,
            'advert_type' => Account::TYPE_YANDEX
        ]);
        if ($account == null) {
            $account                    = new Account();
            $account->company_id        = $company->id;
            $account->stat_type         = -1;
            $account->is_account_common = 0;
            $account->state = Account::STATE_RAW;
            $account->advert_type = Account::TYPE_YANDEX;
            $account->save();
        }

        $this->tokenRequestYandex(Account::SYSTEM_TYPE_CONTEXT, $account->id);
    }

    public function actionConnectMetrika($accountId)
    {
        $account = Account::findOne($accountId);
        if ($account == null || $account->company->user_id != Yii::$app->user->id)
            throw new NotFoundHttpException('Cтраница не найдена.');

        $account->stat_type = Account::TYPE_YANDEX;
        $account->update();

        $this->tokenRequestYandex(Account::SYSTEM_TYPE_WEBANALYTICS, $account->id);
    }

    public function actionUnbindDirect($id)
    {
        $account = Account::findOne($id);
        $account->advert_login = '';
        $account->client_login = '';
        $account->advert_token = '';
        $account->advert_token_expires = '';
        $account->update();

        return $this->redirect([
            'company/view',
            'id' => $account->company_id
        ]);
    }

    public function actionUnbindMetrika($id)
    {
        $account = Account::findOne($id);

backend/views/company/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\Company */
/* @var $form yii\widgets\ActiveForm */
?>

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true])->label('Название') ?>

    <?= $form->field($model, 'website')->textInput(['maxlength' => true])->label('Веб-сайт') ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Добавить' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

backend/views/company/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\CompanySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="company-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'website') ?>

    <?= $form->field($model, 'sales_report_url') ?>

    <?= $form->field($model, 'user_id') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'created_by') ?>

    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/company/create.php
<?php

use backend\widgets\Panel;

/* @var $this yii\web\View */
/* @var $model common\models\Company */

$this->params['leftMenuItems'] = $leftMenuItems;
$this->params['breadcrumbs'] = $breadcrumbs;

Panel::begin(['header' => 'Добавить проект']);
echo $this->render('_form', ['model' => $model]);
Panel::end();

backend/views/company/index.php
<?php

use yii\helpers\Html;
use yiister\gentelella\widgets\grid\GridView;
use yiister\gentelella\widgets\Panel;
use backend\controllers\AccountController;

/* @var $this yii\web\View */
/* @var $searchModel common\models\CompanySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Проекты';
$this->params['leftMenuItems'] = $leftMenuItems;
$this->params['breadcrumbs'] = $breadcrumbs;

Panel::begin(['header' => '']);
echo Html::a('Добавить', ['create'], ['class' => 'btn btn-primary']);
echo GridView::widget([
    'dataProvider' => $dataProvider,
    'bordered' => false,
    'summary' => false,
    'columns' => [
        ['class' => 'yii\grid\SerialColumn'],
        [
            'label' => 'Название',
            'format' => 'raw',
            'value' => function ($data) {
                return Html::a($data->name, ['view', 'id' => $data->id]);
            }
        ],
        [
            'attribute' => 'website',
            'format' => 'url',
        ],
        [
            'format' => 'raw',
            'value' => function($data) {
                return Html::a('<span class="fa fa-edit"></span>',
                    ['company/update', 'id' => $data->id]);
            }
        ]
    ],
]);
Panel::end();

backend/views/company/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Company */

$this->title = $model->name;
$this->params['leftMenuItems'] = $leftMenuItems;
$this->params['breadcrumbs'] = $breadcrumbs;
?>
<div class="company-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/company/view.php
<?php

use yiister\gentelella\widgets\Panel;
use \yii\helpers\Url;
use \common\models\Account;
use yii\bootstrap\Modal;
use yii\widgets\ActiveForm;
use \backend\controllers\AccountController;
use \yii\bootstrap\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Company */
/* @var $direct common\models\Account */

$this->title = $model->name;
$this->params['leftMenuItems'] = $leftMenuItems;
$this->params['breadcrumbs'] = $breadcrumbs;
$this->registerCssFile('/css/company/view.css');
$this->registerJsFile('/js/company/view.js', ['depends' => 'yii\web\YiiAsset']);

Panel::begin(['header' => $model->name]);
?>
    <table class="project">
        <tr>
            <th></th>
            <th>Система контекстной рекламы</th>
            <th>Система веб-аналитики</th>
            <th>CRM-система</th>
        </tr>
        <tr>
            <td>
                <button type="button" class="btn btn-primary">Начать работу</button>
            </td>
            <td>
                <?php if ($direct != null) { ?>
                    <div class="well alert-success">
                        Подключен Яндекс.Директ: <b><?= $direct->advert_login ?></b>
                        <a
                            data-confirm="Вы действительно хотите отключить аккаунт?"
                            href="<?= Url::to(['company/unbind-direct', 'id' => $direct->id])?>">Отключить</a>
                        <?php if ($directClientList !== false) {
                            echo '<div>Данный аккаунт является агентством, аккаунт клиента: ';
                            Modal::begin([
                                'header' => '<h2>Выбор клиента Яндекс.Директ</h2>',
                                'toggleButton' => [
                                    'label' => in_array($direct->client_login, [null, '']) ? 'Выбрать'
                                        : $direct->client_login,
                                    'tag' => 'a'
                                ],
                                'id' => 'directModal'
                            ]);
                            ?>

                            <?php ActiveForm::begin(['action' => 'save-login']); ?>
                            <input type="hidden" value="<?= $direct->id ?>" name="id">
                            <p>Аккаунт Яндекс.Директ: <b><?= $direct->advert_login ?></b>
                                является агентством, выберите клиента:</p>
                            <?php foreach ($directClientList as $client) {
                                printf('<div><label><input type="radio" name="directClient" value="%s" %s> %s</label></div>',
                                    $client,
                                    $client == $direct->client_login ? 'checked' : '',
                                    $client);
                            } ?>
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                            <?php ActiveForm::end(); ?>

                            <?php
                            Modal::end();
                            echo '</div>';

                            if (Yii::$app->session->getFlash('systemType', false) === Account::SYSTEM_TYPE_CONTEXT)
                                $this->registerJs('$(\'#directModal\').modal(\'toggle\')');

                        } ?>
                    </div>
                <?php } else { ?>
                    <div class="well">
                        <a class="connect" href="<?= Url::to(['company/connect-direct', 'id' => $model->id])?>">
                            Подключить Яндекс.Директ</a>
                    </div>
                <?php } ?>
            </td>
            <td>
                <?php if ($direct != null && $direct->stat_login != null) { ?>
                    <div class="well alert-success">
                        <?php if ($direct->stat_type == Account::TYPE_YANDEX) { ?>

                            <div>
                                Подключена Яндекс.Метрика: <b><?= $direct->advert_login ?></b>
                                <a
                                    data-confirm="Вы действительно хотите отключить аккаунт?"
                                    href="<?= Url::to(['company/unbind-metrika', 'id' => $direct->id])?>">Отключить</a>
                            </div>

                            <div>
                                Счетчик:
                                <?php
                                Modal::begin([
                                    'header' => '<h2>Выбор счетчика Яндекс.Метрика</h2>',
                                    'toggleButton' => [
                                        'label' => $direct->counter == null ? 'выбрать'
                                            : $direct->counter . ' (' . count($directSelectedGoals) . ' целей)',
                                        'tag' => 'a'
                                    ],
                                    'id' => 'metrikaModal'
                                ]);
                                ?>

                                <?php ActiveForm::begin(['action' => 'save-goals']); ?>
                                <input type="hidden" value="<?= $direct->id ?>" name="id">
                                Счетчик: <select name="counter" class="counter">
                                    <?php foreach ($directMetrikaCounters as $counter) {
                                        printf('<option value="%s" %s>%s</option>',
                                            $counter['id'],
                                            $counter['id'] == $direct->counter ? 'selected' : '',
                                            $counter['id'] . ' - ' . $counter['name']);
                                    } ?>
                                </select>
                                <div class="goals-selector">
                                    Цели:
                                    <?php foreach ($directMetrikaCounters as $counter) { ?>
                                        <div class="goals goals-<?= $counter['id'] ?>">
                                            <?php foreach ($counter['goals'] as $goal) {
                                                printf('<div><label>
                                                    <input type="checkbox" name="goal[]" value="%s" %s /> %s</label></div>',
                                                    $goal['id'],
                                                    in_array($goal['id'], $directSelectedGoals) ? 'checked' : '',
                                                    $goal['name']);
                                            } ?>
                                        </div>
                                    <?php } ?>
                                </div>
                                <button type="submit" class="btn btn-primary">Сохранить</button>
                                <?php ActiveForm::end(); ?>

                                <?php
                                Modal::end();

                                if (Yii::$app->session->getFlash('systemType', false) === Account::SYSTEM_TYPE_WEBANALYTICS)
                                    $this->registerJs('$(\'#metrikaModal\').modal(\'toggle\')');

                                ?>
                            </div>

                        <?php } else {
                            echo 'Google.Analytics: ' . $direct->advert_login;
                        } ?>
                    </div>
                <?php } else { ?>
                    <div class="well">
                        <?php if ($direct == null) { ?>
                            Сначала подключите Яндекс.Директ
                        <?php } else { ?>
                            <a class="connect" href="<?= Url::to(['company/connect-metrika', 'accountId' => $direct->id])?>">
                                Подключить Яндекс.Метрика</a>
                            или
                            <a class="connect">Подключить Google.Analytics</a>
                        <?php } ?>

                    </div>
                <?php } ?>
            </td>
            <td rowspan="2">
                <div class="well <?= in_array($model->sales_report_url, ['', null]) ? '' : 'alert-success' ?>">
                    <?php
                    Modal::begin([
                        'header' => '<h2>Подключение CRM</h2>',
                        'toggleButton' => [
                            'label' => in_array($model->sales_report_url, ['', null]) ? 'Подключить'
                                : 'Адрес отчета: ' . $model->sales_report_url,
                            'tag' => 'a'
                        ],
                    ]);
                    ?>
                    <p>Для использования данных из CRM-системы, введите адрес,
                        по которому возможно получать ежедневную выгрзку статистики:</p>

                    <?php ActiveForm::begin(['action' => 'save-crm']); ?>
                    <input type="hidden" value="<?= $model->id ?>" name="id">
                    <input type="text" name="crm" class="crm-field"
                       placeholder="https://mywebsite.ru/crm/export_orders?someparameters"
                       value="<?= in_array($model->sales_report_url, ['', null]) ? '' : $model->sales_report_url ?>">
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                    <?php ActiveForm::end(); ?>

                    <?php
                    Modal::end();
                    ?>
                </div>
            </td>
        </tr>
        <tr>
            <td>
                <button type="button" class="btn btn-primary">Начать работу</button>
            </td>
            <td>
                <div class="well">
                <?php
                if ($adwords == null) {
                    if ($customerId != null) {
                        printf('<p>Введен Customer ID: %s,<br>ожидайте подключения</p>', $customerId);
                        echo Html::a('Проверить',
                            [
                                'company/connect-adwords',
                                'id' => $model->id
                            ]);
                        echo Html::a('Отвязать',
                            [
                                'company/unbind-customer-id',
                                'id' => $model->id,
                                'customerId' => $customerId
                            ]);
                    } else {
                        Modal::begin([
                            'header' => '<h2>Подключение Google.AdWords</h2>',
                            'toggleButton' => [
                                'label' => 'Подключить Google.AdWords',
                                'tag' => 'a'
                            ],
                        ]);
                        ?>
                        <p>Введите десятизначный номер Customer ID:</p>

                        <?php ActiveForm::begin(['action' => 'save-customer-id']); ?>
                        <input type="hidden" value="<?= $model->id ?>" name="id">
                        <input type="text" name="customerId" class="crm-field" placeholder="123-456-7890">
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <?php
                        ActiveForm::end();
                        Modal::end();
                    }
                }
                ?>
                </div>
            </td>
            <td>
                <div class="well">
                    <a class="connect">Подключить Яндекс.Метрика</a>
                    или
                    <a class="connect">Подключить Google.Analytics</a>
                </div>
            </td>
        </tr>
    </table>
<?php
Panel::end();